# SITE SETTINGS
title: Vespa-Watch
author: INBO
url: # TODO

# THEME SETTINGS
theme: minima
remote_theme: peterdesmet/petridish # TODO: set version
github_edit: true
colors:
  links: "#ea792a"  # Orange
  banner: "#73984a" # Green
  footer: "#3c3c3c" # Gray
font_serif: false
rounded_corners: true
logo: /assets/images/logo.png

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: pages/nl
    values:
      lang: nl
      permalink: /:basename/
  - scope:
      path: pages/en
    values:
      lang: en
      permalink: /en/:basename/
